#!/bin/bash

faSomeRecords /share/malooflab/John/KIAT/CAP3/Pre_Evidential_Da_Ae/Da_Ae_Trinity.fasta.cap.contigs Zero_Hit_CAP3_Contigs_Da_Ae_Blast No_Match_Contigs/Zero_Hit_CAP3_Contigs_Da_Ae
faSomeRecords /share/malooflab/John/KIAT/CAP3/Pre_Evidential_Da_Ol_1/Da_Ol_1_Trinity.fasta.cap.contigs Zero_Hit_CAP3_Contigs_Da_Ol_1_Blast No_Match_Contigs/Zero_Hit_CAP3_Contigs_Da_Ol_1
faSomeRecords /share/malooflab/John/KIAT/Evidential_Gene/Post_CAP3_Da_Ae/okayset/R_Post_CAP3_Da_Ae.okay.fasta Zero_Hit_CAP3_Evidential_Da_Ae_Blast No_Match_Contigs/Zero_Hit_CAP3_Evidential_Da_Ae
faSomeRecords /share/malooflab/John/KIAT/Evidential_Gene/Post_CAP3_Da_Ol_1/okayset/R_Post_CAP3_Da_Ol_1.okay.fasta Zero_Hit_CAP3_Evidential_Da_Ol_1_Blast No_Match_Contigs/Zero_Hit_CAP3_Evidential_Da_Ol_1
faSomeRecords /share/malooflab/John/KIAT/CAP3/Pre_Evidential_Da_Ae/Da_Ae_Trinity.fasta.cap.singlets Zero_Hit_CAP3_Singlets_Da_Ae_Blast No_Match_Contigs/Zero_Hit_CAP3_Singlets_Da_Ae
faSomeRecords /share/malooflab/John/KIAT/CAP3/Pre_Evidential_Da_Ol_1/Da_Ol_1_Trinity.fasta.cap.singlets Zero_Hit_CAP3_Singlets_Da_Ol_1_Blast No_Match_Contigs/Zero_Hit_CAP3_Singlets_Da_Ol_1
faSomeRecords /share/malooflab/John/KIAT/CAP3/Post_Evidential_Da_Ae/Da_Ae_Trinity.okay.fasta.cap.contigs Zero_Hit_Evidential_CAP3_Contigs_Da_Ae_Blast No_Match_Contigs/Zero_Hit_Evidential_CAP3_Contigs_Da_Ae
faSomeRecords /share/malooflab/John/KIAT/CAP3/Post_Evidential_Da_Ol_1/Da_Ol_1_Trinity.okay.fasta.cap.contigs Zero_Hit_Evidential_CAP3_Contigs_Da_Ol_1_Blast No_Match_Contigs/Zero_Hit_Evidential_CAP3_Contigs_Da_Ol_1
faSomeRecords /share/malooflab/John/KIAT/CAP3/Post_Evidential_Da_Ae/Da_Ae_Trinity.okay.fasta.cap.singlets Zero_Hit_Evidential_CAP3_Singlets_Da_Ae_Blast No_Match_Contigs/Zero_Hit_Evidential_CAP3_Singlets_Da_Ae
faSomeRecords /share/malooflab/John/KIAT/CAP3/Post_Evidential_Da_Ol_1/Da_Ol_1_Trinity.okay.fasta.cap.singlets Zero_Hit_Evidential_CAP3_Singlets_Da_Ol_1_Blast No_Match_Contigs/Zero_Hit_Evidential_CAP3_Singlets_Da_Ol_1
faSomeRecords /share/malooflab/John/KIAT/Evidential_Gene/Pre_CAP3_Da_Ae/okayset/R_Da_Ae_Trinity.okay.fasta Zero_Hit_Evidential_Da_Ae_Blast No_Match_Contigs/Zero_Hit_Evidential_Da_Ae
faSomeRecords /share/malooflab/John/KIAT/Evidential_Gene/Pre_CAP3_Da_Ol_1/okayset/R_Da_Ol_1_Trinity.okay.fasta Zero_Hit_Evidential_Da_Ol_1_Blast No_Match_Contigs/Zero_Hit_Evidential_Da_Ol_1
faSomeRecords /share/malooflab/John/KIAT/Trinity_Runs/trinity_out_Da_Ae/Trinity.fasta Zero_Hit_Original_Da_Ae_Blast No_Match_Contigs/Zero_Hit_Original_Da_Ae
faSomeRecords /share/malooflab/John/KIAT/Trinity_Runs/trinity_out_Da_Ol_1/Trinity.fasta Zero_Hit_Original_Da_Ol_1_Blast No_Match_Contigs/Zero_Hit_Original_Da_Ol_1
